---
- name: Install soft
  hosts: all
  roles: 
  - common
  - sshsudo   # for troubleshooting
  
 
# java is included (meta)  for jenkins, nexus
 
- name: Install jenkins
  hosts: jenkins
  tags: jenkins
  roles:
  - role: jenkins

- name: Install nexus  
  hosts: nexus
  tags: nexus
  roles:
  - role: nexus
  
  
- name: Install nginx
  hosts: nginx
  tags: nginx
  roles:
#  - common
#  - sshsudo
  - nginx
              
  
- name: deploy to tomcat
  hosts: workstation
  tags: deploy
  roles:
  - deploy
          
          
          

- name: Install tomcat
  hosts: sonar
  tags: tomcat
  roles:
  - common
  - sshsudo
  - tomcat
#  become: yes

#  vars:
#    user: jenkins
#    gid: 2000
#    uid: 2000
# roles:
#  - role: jenkins
#    vars:
#      user: jenkins
#      gid: 2000
#      uid: 2000
#  - role: user
#    vars:
#      user: jenkins
#      gid: 2000
#      uid: 2000

#- name : install jenkins
#  hosts:  jenkins
#  vars: {user=jenkins, gid=2000, uid=2000}


#    vars: {user=jenkins, gid=2000, uid=2000} 

#- name: Install sonar
#  hosts: jenyaslv1
#  roles:
#  - sonar

#- name: Install nexus
#  hosts: nexus
#  roles:
#  - jenkins_user
#  - nexus_user
#  - nexus_nginx
#  - nexus_install
#  become: yes

