---
#- name : install jenkins
#  hosts:  jenkins
#  vars: {user=jenkins, gid=2000, uid=2000}

#   - jenyaslv2
#   - nexus
#   - tomcat
- hosts: jenkins
  roles:
  - role: jenkins
    vars:
      user: jenkins
      gid: 2000
      uid: 2000
  - role: user
    vars:
      user: jenkins
      gid: 2000
      uid: 2000



#    vars: {user=jenkins, gid=2000, uid=2000} 

#- name: Install sonar
#  hosts: jenyaslv1
#  roles:
#  - sonar_user
#  - sonar

#- name: Install nexus
#  hosts: nexus
#  roles:
#  - jenkins_user
#  - nexus_user
#  - nexus_nginx
#  - nexus_install
#  become: yes

#- name: Install tomcat
#  hosts: tomcat
#  roles:
#  - tomcat_install
#  become: yes
          

