---
- name: Install soft
  hosts: all, !workstation
  tags: common
  roles:
  - common
 
- name: Install jenkins
  hosts: jenkins
  tags: jenkins
  roles:
  - role: jenkins
  

- name: Install nexus  
  hosts: nexus
  tags: nexus
  roles:
  - role: nexus


- name: Install sonar
  hosts: sonar
  tags: sonar
  roles:
  - sonar
  
- name: Install nginx
  hosts: nginx
  tags: nginx
  roles:
  - nginx

- name: Install tomcat
  hosts: sonar
  tags: tomcat
  roles:
  - tomcat

- name: deploy to tomcat
  hosts: workstation
  tags: deploy
  roles:
  - deploy


#- name: Install sshsudo
#  hosts: all, !workstation
#  tags: usersshsudo
#  roles:
#  - usersudossh 

#- name: test
#  hosts: sonar
#  tags: test
#  roles:
#  - test





