---
 
- name: Install jenkins
  hosts: jenkins
  tags: jenkins
  roles:
  - role: jenkins
#  - role: common
#  - role: sshsudo
  

- name: Install nexus  
  hosts: nexus
  tags: nexus
  roles:
  - role: nexus


- name: Install sonar
  hosts: sonar
  tags: sonar
  roles:
  - sonar
        
  
  
- name: Install nginx
  hosts: nginx
  tags: nginx
  roles:
#  - common
#  - sshsudo
  - nginx
              
  
- name: deploy to tomcat
  hosts: workstation
  tags: deploy
  roles:
  - deploy
          

- name: Install tomcat
  hosts: sonar
  tags: tomcat
  roles:
#  - common
#  - sshsudo
  - tomcat

- name: Install soft
  hosts: all, !workstation
  tags: common
  roles:
  - common
  - sshsudo   # for troubleshooting
          


#  vars:
#    user: jenkins
#    gid: 2000
#    uid: 2000
# roles:
#  - role: jenkins
#    vars:
#      user: jenkins
#      gid: 2000
#      uid: 2000
#  - role: user
#    vars:
#      user: jenkins
#      gid: 2000
#      uid: 2000

#- name : install jenkins
#  hosts:  jenkins
#  vars: {user=jenkins, gid=2000, uid=2000}


#    vars: {user=jenkins, gid=2000, uid=2000} 

