---

- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  become: yes
        
- name:  start service nexus
  service: name=nexus.service enabled=yes  state=started
  become: yes
            


- name: save nexus fact
  copy: 
    content: |
      {
        "version": "{{ nexus_version.stdout }}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/nexus.fact
  become: yes