---
- name: Create  group 
  group:
    name: "{{ user }}"
    state: present
    gid: "{{ gid }}"
  become: yes
- debug: msg="Created group- {{user}} with gid- {{gid}}"


  
- name: Create  user 
  user:
    name: "{{ user }}"
    append: yes
    uid: "{{ uid }}"
    group: "{{ gid }}"
  become: yes
- debug: msg="Created user- {{user}} and added to gid- {{gid}}"



