---
- name: Create  group 
  group:
    name: "{{ group }}"
    state: present
    gid: "{{ gid }}"
  become: yes
- debug: msg="Created group- {{group}} with gid- {{gid}}"

# - gid: "{{users.{{devops_user}}.gid}}"
# - uid: "{{users.{{devops_user}}.uid}}"

  
- name: Create  user 
  user:
    name: "{{ user }}"
    append: yes
    uid: "{{ uid }}"
    group: "{{ gid }}"
  become: yes
- debug: msg="Created user- {{user}} and added to gid- {{gid}}"



