---


- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  become: yes

- name:  start service tomcat
  service: name=tomcat.service enabled=yes  state=started
  become: yes
            
- name: get tomcat version
  shell: |
      /opt/apache-tomcat-9.0.17/bin/version.sh | grep 'Server version'| cut -f 2
  register: tomcat_version
        

- name: save tomcat fact
  copy: 
    content: |
      {
        "version": "{{ tomcat_version.stdout }}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/tomcat.fact
  become: yes