---


- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  become: yes

- name:  start service tomcat
  service: name=tomcat.service enabled=yes  state=started
  become: yes
            

- name: save tomcat fact
  copy: 
    content: |
      {
        "version": "{{ tomcat_version.stdout }}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/tomcat.fact
  become: yes