---
- name: Create  group 
  group:
    name: "{{ user_name }}"
    state: present
    gid: 8000
  become: yes
  
- name: Create  user 
  user:
    name: "{{ user_name }}"
    append: yes
    uid: 8000
    group: 8000
  become: yes

#for troubleshooting
- name: Add sudoers priveleges  in a separate file
  copy:
    dest: /etc/sudoers.d/{{ user_name }}
    content: " {{ user_name }} ALL=(ALL) NOPASSWD:ALL"
  become: yes