---
#- name: include sshaccess
#  include: sshaccess.yml  #old kind

- name: Add sudoers priveleges  in a separate file
  copy:
    content: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/{{ user }}
  become: yes


- name: copy ssh pub.key
  authorized_key:
    user: "{{user}}"
    state: present
    key: '{{item}}'
#  debug: msg="{{item}}"
  with_file:
    - files/id_rsa.pub
  become: yes