---
- name: Create ssh dir
  file:
    path: /home/{{ user }}/.ssh/
    state: directory
    mode: 0700
    owner: "{{ user }}"
    group: "{{ user }}"
  become: yes

#- name: Configure ssh access with ssh-keys for user  from current user
#  authorized_key:
#    user: "{{ user_name }}"
#    state: present
#    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
#  become: yes


