---
- name: create user tomcat
  user:
    name: tomcat
    password: "{{ 'tomcat' | password_hash('sha512') }}"

- name: wget tomcat
  get_url:
    url: http://ftp.byfly.by/pub/apache.org/tomcat/tomcat-9/v9.0.17/bin/apache-tomcat-9.0.17.tar.gz
    dest: /opt/
    owner: tomcat
    group: tomcat

- name: unarchive tar.gz
  unarchive:
    src: '/opt/apache-tomcat-9.0.17.tar.gz'
    dest: /opt/
    remote_src: yes

- name: chown
  file:
    path: '/opt/apache-tomcat-9.0.17'
    owner: tomcat
    group: tomcat
    state: directory
    recurse: yes

- name: creating service
  blockinfile:
    path: /etc/systemd/system/tomcat.service
    block: |
      [Unit]
      Description=Tomcat - instance %i
      After=syslog.target network.target
      [Service]
      Type=forking
      User=tomcat
      Group=tomcat
      Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
      Environment="CATALINA_HOME=/opt/apache-tomcat-9.0.17"
      Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
      ExecStart=/opt/apache-tomcat-9.0.17/bin/startup.sh
      ExecStop=/opt/apache-tomcat-9.0.17/bin/shutdown.sh
      [Install]
      WantedBy=multi-user.target
    create: True

- name: enable tomcat
  service: name=tomcat.service enabled=yes state=started