---
dependencies:
- role: java
- role: user
  vars:
  - group: "{{ jenkins_group}}"
###  - group: "{{ jenkins_group}} | default({{jenkins_user}})"
  - user: "{{jenkins_user}}"
  - gid: "{{users[jenkins_group].gid}}"
  - uid: "{{users[jenkins_user].uid}}"
