---

- name: get jenkins dir
  stat: path="{{nexus_home}}"
  register: nexusdir
      

- include:   install.yml
  when: not  nexusdir.stat.exists

- include:  configure.yml
  when: not  nexusdir.stat.exists
  


- name: Get nexus version
  shell: |
      curl -Is http://localhost:8081/ | grep Server | awk '{print $2}' | awk -F '/' '{print $2}'
  args:
    warn: false
  register: nexus_version
  notify: save nexus fact
          