---
- name: restart-nginx
  service: name=nginx state=restarted enabled=yes
  become: yes

- name: save nginx fact
  copy:
    content: |
      {
        "version": "{{ nginx_version.stdout }}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/nginx.fact
  become: yes