---
- name: save java fact
  copy:
    content: |
      {
        "version": "{{ java_version.stdout }}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/java.fact
  become: yes