---
- name: Install java
  yum: name="{{ java_version }}" state=present
  become: yes
  
- debug: msg="installed {{ java_version}}"


- name: Java Version
  shell:    java -version 2>&1 | grep version | awk '{print $3}' | sed 's/[^0-9._]//g'
  register: java_version
  args:
    warn: no
  notify: save java fact

###add   fact
#- file: path=/etc/ansible/facts.d state=directory
#  become: yes
# ???  listen: save java fact
