---
- name: create project directory
  file:
    state: directory
    path: /opt/jenkins
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
  become: yes

- name: download sources file
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /opt/jenkins/jenkins.war
  become: yes

- name: copy jenkins.service file
  copy:
    src: jenkins.service
    dest: /etc/systemd/system/ #multi-user.target.wants
    mode: 0755
  notify:
    - systemd daemon reload
    - restart service jenkins
  become: yes



