---
- name: create project directory
  file:
    state: directory
    path: /opt/jenkins
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
  become: yes

- name: download sources file
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /opt/jenkins/jenkins.war
  become: yes

- name: copy jenkins.service file
  copy:
    src: jenkins.service
    dest: /etc/systemd/system/ #multi-user.target.wants
    mode: 0755
  notify:
    - systemd daemon reload
    - restart service jenkins
  become: yes

# workaround
- meta: flush handlers

- name: Check if jenkins is installed
  command: systemctl status docker
  register: jenkins_check
  ignore_errors: yes

- name: reStart jenkins service
  service:
    name: jenkins
    state: restarted
    enabled: yes
  when:
  - jenkins_check.msg is defined
  - jenkins_check.msg.find('No such file or directory') != -1
