---
- name: create project directory
  file:
    state: directory
    path: "{{jenkins_home}}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
  become: yes

- name: download source file
  get_url:
    url: http://mirrors.jenkins.io/war-stable/{{jenkins_version}}/jenkins.war
    dest: "{{jenkins_home}}/jenkins.war"
  become: yes

- name: template  jenkins.service file
  template:
    src: jenkins.j2
    dest: /etc/systemd/system/{{jenkins_user}}.service #multi-user.target.wants
    mode: 0755
  notify:
    - systemd daemon reload
    - start service jenkins
#    - save jenkins fact
  become: yes

- name: Get jenkins version
  command: java -jar "{{jenkins_home}}/jenkins.war" --version
  register: jenkins_version
  notify: save jenkins fact
  become : yes