---
- name:  initializate  DB postgre
  command: "postgresql-setup initdb"
  args: 
    creates: /var/lib/pgsql/data/PG_VERSION
  become: yes
  become_user: postgres
      
    
- name: copy  pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/data/
  notify: start service postgre
  become: yes
  become_user: postgres
      

#- name: start service postgre
#  notify: start service postgre

- name: force start service postgre
  meta: flush_handlers 

- name: Configuration postgresql
  shell: |
    psql  -c "create user sonar"
    psql  -c "alter role sonar with createdb"
    psql  -c "alter user sonar with encrypted password 'sonar'"
    psql  -c "create database sonar owner sonar"
    psql  -c "grant all privileges on database sonar to sonar"
  become: yes
  become_user: postgres


- name: Get postgres version
  shell: |
    postgres -V | awk '{print $NF}'
  register: postgre_version
  notify:
  - restart service postgre
  - save postgre fact
