---
- name: get postgre dir
  stat: path="{{postgre_home}}"
  register: postgredir
    
- include:   install.yml
  when: not  postgredir.stat.exists
      

- include: install.yml
  when: not  postgredir.stat.exists
  