---
- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  become: yes

- name:  start service sonar
  service: name=sonar.service enabled=yes  state=started
  become: yes
  
  
- name: save sonar fact
  copy:
    content: |
      {
            "installed": "{{ ansible_date_time.iso8601 }}",
            "sonar_version": "{{ sonar_version }}"
      }
    dest: /etc/ansible/facts.d/sonar.fact
  become: yes
                                                                  
