---
- name: wget  and unzip sonar
  unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.zip
    dest: /opt/
    remote_src: yes
    owner: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    creates: "/opt/sonarqube-6.7/COPYING"


