---
- name: get sonar dir
  stat: path="{{sonar_home}}"
  register: sonardir
    
- include:   install.yml
  when: not  sonardir.stat.exists
      
- include:   configure.yml
#  when: not  sonardir.stat.exists
  