---
- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  become: yes

- name:  start service postgre
  service: name=postgresql.service enabled=yes  state=started
  become: yes

- name:  restart service postgre
  service: name=postgresql.service enabled=yes  state=restarted
  become: yes
  
#- name: save postgresql fact
#  copy:
#      content: |
#        {
#        "version": "{{ jenkins_version.stdout }}",
#        "installed": "{{ ansible_date_time.iso8601 }}",
#        "jenkins_home": "{{ jenkins_home }}",
#        "jenkins_user": "{{ jenkins_user }}",
#        "jenkins_group": "{{ jenkins_group }}",
#        "jenkins_execstart": "{{jenkins_execstart}}"
#              }
#      dest: /etc/ansible/facts.d/postgresql.fact
#  become: yes

