---
- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  become: yes

- name:  start service postgre
  service: name=postgresql.service enabled=yes  state=started
  become: yes

- name:  restart service postgre
  service: name=postgresql.service enabled=yes  state=restarted
  become: yes
 
 
- name: save postgre fact
  copy:
    content: |
      { 
        "version": "{{ postgre_version.stdout }}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/postgre.fact
  become: yes
