---
- name: Install postgresql server and contrib
  package: 
    name:
      - postgresql-server
      - postgresql-contrib
    state: installed

- name: Postgres init DB
  command: "postgresql-setup initdb"
  args: 
    creates: /var/lib/pgsql/data/PG_VERSION

- name: copy  pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/data/
    force: yes

- name: Enable postgresql
  service: 
    name: postgresql 
    enabled: yes 
    state: started

- name: Configuration postgresql
  shell: |
    psql  -c "create user sonar"
    psql  -c "alter role sonar with createdb"
    psql  -c "alter user sonar with encrypted password 'sonar'"
    psql  -c "create database sonar owner sonar"
    psql  -c "grant all privileges on database sonar to sonar"
  become: yes
  become_user: postgres

- name: Restart postgresql
  service: 
    name: postgresql 
    state: reloaded
  changed_when: no